vuhaisan/config/routes.rb
Vuhaisan::Application.routes.draw do
  scope "admin" do
    resources :products
    resources :categories
    resources :admin_sessions, only: [:new, :create]
    resources :settei, only: [:edit, :update]
    resources :users, only: [:index]
    resources :orders, only: [:index, :edit, :update]
    resources :kensakus, only: [:index]
    match "logout", to: "admin_sessions#logout", as: :admin_logout
    match "categories_index_update/:id", to: "categories#categories_index_update", as: :admin_categories_index_update
  end

  scope "client" do
    match "home", to: "client#home", as: :client_home
    match "product/:id", to: "client#product_detail", as: :client_product_detail
    match "add_to_cart", to: "client#add_to_cart", as: :client_add_to_cart
    match "add_to_cart_remote", to: "client#add_to_cart_remote", as: :client_add_to_cart_remote, format: :js
    match "remove_from_cart_remote", to: "client#remove_from_cart_remote", as: :client_remove_from_cart_remote_remote, format: :js
    match "cart", to: "client#cart_detail", as: :client_cart_detail
    match "confirm", to: "client#confirm", as: :client_confirm
    match "profile", to: "client#profile", as: :client_profile
    match "update_profile", to: "client#update_profile", as: :client_update_profile
    match "login_remote", to: "client#login_remote", as: :client_login_remote, format: :js
    match "logout", to: "client#logout", as: :client_logout
    match "logout_remote", to: "client#logout_remote", as: :client_logout_remote
    match "update_order_delivery_info", to: "client#update_order_delivery_info", as: :client_update_order_delivery_info
    match "delete_cart", to: "client#delete_cart", as: :client_delete_cart
    match "order/:code", to: "client#order", as: :client_order
    match "info", to: "client#info", as: :client_info
  end
  scope "payment" do
    match "vtc", to: "payment#vtc", as: :payment_vtc
  end

end

vuhaisan/app/views/layouts/_client_footer.html.erb
<div id="footer" class="display:none;">
  <table style="width:100%">
    <tr>
      <td>
      	<%= CONTACT_EMAIL_ADDRESS %>
      	<br/>
        <br/>
      	Địa điểm giao dịch: 229/64/41 đường Tây Thạnh - Phường Tây Thạnh - Quận Tân Phú
      </td>
      <td align="right" style="padding-right:30px;vertical-align:top;">
        <div>
          <%= link_to t('client.policy'), "#{client_info_path}#policy", target: '_blank',
                style: 'color:white !important;' %>
        </div>

        <div>
          <%= link_to t('client.payment_hint'), "#{client_info_path}#pay_at_delivery", target: '_blank',
                style: 'color:white !important; margin-top:5px' %>
        </div>
        
        <div>
          <%= link_to t('client.search_hint'), "#{client_info_path}#search_hint", target: '_blank',
                style: 'color:white !important;' %>
        </div>
      </td>
    </tr>
  </table>
</div>

vuhaisan/app/views/layouts/_fb_check.html.erb
<img id="fbCheckImg" src="https://facebook.com/favicon.ico" style="display:none;" />
<script type="text/javascript">
	var fbAccessible = false;
	$('#fbCheckImg').load(function() {
		fbAccessible = true;
	});
	setTimeout(function() {
		if (!fbAccessible) {
			$(".fbsp").remove();
		}
	}, 500);
</script>

vuhaisan/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <% title = @title || "Please set title" %>
  <title><%=title%></title>
  <%= stylesheet_link_tag "admin" %>
  <%= javascript_include_tag "admin" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <%= 
      link_to(
        t("admin.product"),
        products_path,
        {
          class: (@tab==0?"selected_tab":"")
        }
      )
    %>
    <%=
      link_to(
        t("admin.category"),
        categories_path,
        {
          class: (@tab==1?"selected_tab":""),
          style: "margin-left:10px;"
        }
      )
    %>
    <%=
      link_to(
        t("admin.settei"),
        edit_settei_path(@settei.id.to_s),
        {
          class: (@tab==2?"selected_tab":""),
          style: "margin-left:10px;"
        }
      )
    %>
    <%=
      link_to(
        t("admin.user"),
        users_path,
        {
          class: (@tab==3?"selected_tab":""),
          style: "margin-left:10px;"
        }
      )
    %>
    <%=
      link_to(
        t("admin.order"),
        orders_path,
        {
          class: (@tab==4?"selected_tab":""),
          style: "margin-left:10px;"
        }
      )
    %>
    <%=
      link_to(
        t("admin.kensaku"),
        kensakus_path,
        {
          class: (@tab==5?"selected_tab":""),
          style: "margin-left:10px;"
        }
      )
    %>
    <%= link_to(
          t("admin.logout"),
          admin_logout_path,
          method: :delete,
          style: "float:right;"
        )%>
  </div>
  <hr/>

  <% if @error %>
    <div class="error_box">
      <%= @error %>
    </div>
  <% end %>

  <h3><%= title %></h3>

  <%= yield %>

</body>
</html>

vuhaisan/app/views/layouts/client.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "Please set title" %></title>
  <%= stylesheet_link_tag "client" %>
  <%= javascript_include_tag "client" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="fb-root"></div>
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '<%= get_fb_id(request) %>',
        status     : true,
        cookie     : true,
        xfbml      : true
      });
      onFbAsyncInit("<%= client_login_remote_path %>", "<%=  client_logout_remote_path %>");
    };

    $(function() {
      (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    });
  </script>

  <ul class="bxslider">
    <li><img src="http://s7.postimg.org/g7y5c34yz/background_map.jpg" class='bannerImg'/></li>
    <li><img src="http://s28.postimg.org/l0nnwyaql/background_map2.png" class='bannerImg'/></li>
  </ul>

  <script type="text/javascript">
    $('.bxslider').bxSlider({
      auto: true,
      controls: false,
      pager: false,
      speed: 1000,
      useCSS: true,
      autoHover: true
    });
  </script>

  <div id="menuBar">
    <div id="categoryList">
      <div class="wrapper">
      <% @categories.each_with_index do |c, i| %>
        <div class="<%= @category_id == c.id.to_s ? "selected" : "col" %>">
          <%= link_to(
                  c.name,
                  client_home_path(category_id:c.id),
                ) %>
        </div>
      <% end %>
      </div>
    </div>

    <div id="userInfo">
      <a href="<%= client_cart_detail_path %>">
        <div class="col cart_image"><%= image_tag "cart.png", id: 'cartIconImg' %></div>
        <div class="col cart_label" ><%= t("client.cart") %></div>
        <div class="col cart_count"><%= @cart.sum_quantity %></div>
      </a>
      <div class="col fbAccount">
        <a id="profileLink" href="<%= client_profile_path %>">
          <span class="name"></span>
          <img class="profilePic"></img>
        </a>
        <button class="loginButton"></button>
      </div>
      </a>
    </div>

    <div id='searchBox'>
      <%= form_tag client_home_path, method: :post do %>
        <%= text_field_tag :keyword, @keyword, placeholder: t('client.search') %>
        <%= link_to '[?]', "#{client_info_path}#search_hint", target: '_blank' %>
      <% end %>
    </div>
  </div>

  <div id="contentDiv">
    <%= yield %>
  </div>

  <%= render partial: 'layouts/client_footer' %>

  <script type="text/javascript">
    client();
  </script>

</body>
</html>