vuhaisan/config/routes.rb
Vuhaisan::Application.routes.draw do
  scope "admin" do
    resources :products
    resources :categories
    resources :admin_sessions, only: [:new, :create]
    resources :settei, only: [:edit, :update]
    resources :users, only: [:index]
    resources :orders, only: [:index, :edit, :update]
    resources :kensakus, only: [:index]
    match "logout", to: "admin_sessions#logout", as: :admin_logout
    match "categories_index_update/:id", to: "categories#categories_index_update", as: :admin_categories_index_update
  end

  scope "client" do
    match "home", to: "client#home", as: :client_home
    match "product/:id", to: "client#product_detail", as: :client_product_detail
    match "add_to_cart", to: "client#add_to_cart", as: :client_add_to_cart
    match "add_to_cart_remote", to: "client#add_to_cart_remote", as: :client_add_to_cart_remote, format: :js
    match "remove_from_cart_remote", to: "client#remove_from_cart_remote", as: :client_remove_from_cart_remote_remote, format: :js
    match "cart", to: "client#cart_detail", as: :client_cart_detail
    match "confirm", to: "client#confirm", as: :client_confirm
    match "profile", to: "client#profile", as: :client_profile
    match "update_profile", to: "client#update_profile", as: :client_update_profile
    match "login_remote", to: "client#login_remote", as: :client_login_remote, format: :js
    match "logout", to: "client#logout", as: :client_logout
    match "logout_remote", to: "client#logout_remote", as: :client_logout_remote
    match "update_order_delivery_info", to: "client#update_order_delivery_info", as: :client_update_order_delivery_info
    match "delete_cart", to: "client#delete_cart", as: :client_delete_cart
    match "order/:code", to: "client#order", as: :client_order
    match "info", to: "client#info", as: :client_info
  end
  scope "payment" do
    match "vtc", to: "payment#vtc", as: :payment_vtc
  end

end

vuhaisan/app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :unit, type: String # kg, lit, cai, v.v...
  field :price, type: Integer
  field :quantity, type: Integer
  field :images, type: Array
  field :desc, type: String

  field :data, type: String
  field :flattened_data, type: String

  field :custom_fields, type: Hash, default: {}
  field :tags, type: Array, default: []

  field :hidden, type: Boolean, default: false

  belongs_to :category, class_name: Category.name, inverse_of: :products
  has_many :order_items, class_name: OrderItem.name, inverse_of: :product

  before_destroy do |document|
    if document.images
      document.images.each do |i|
        Product.delete_image i
      end
    end
  end

  before_save do |document|
    a = get_search_data document, [
      :name, :unit_as_text, :price, :in_store_as_text, :category_as_text]
    document.data = a[0]
    document.flattened_data = a[1]

    if document.category_id_changed?
      document.hidden = document.category.hidden
    end

    # BUILD CATEGORY 'S TAG TREE
    pid = document.id.to_s
    if document.persisted?
      if document.category_id_changed?
        origin_product = Product.where(id: pid).only(:category_id, :tags).first
        if  origin_product.tags.length > 0
          old_category = origin_product.category
          __delete_pid_from_category_tag_tree(old_category.tag_tree, pid)
          __recalculate_category_tag_tree_pcount(old_category.tag_tree)
          __purge_category_tag_tree(old_category.tag_tree)
          old_category.save
        end
        if document.tags.length > 0
          new_category = document.category
          __add_tags_to_category_tag_tree(new_category.tag_tree, document.tags, pid)
          __recalculate_category_tag_tree_pcount(new_category.tag_tree)
          new_category.save
        end
      elsif document.tags_changed?
        category = document.category
        __delete_pid_from_category_tag_tree(category.tag_tree, pid)
        __add_tags_to_category_tag_tree(category.tag_tree, document.tags, pid)
        __recalculate_category_tag_tree_pcount(category.tag_tree)
        __purge_category_tag_tree(category.tag_tree)
        category.save
      end
    else
      if document.tags.length > 0
        category = document.category
        __add_tags_to_category_tag_tree(category.tag_tree, document.tags, pid)
        __recalculate_category_tag_tree_pcount(category.tag_tree)
        category.save
      end
    end
  end

  def __purge_category_tag_tree(node)
    node['children'].each do |child|
      if child['pcount'] == 0
        node['children'].delete(child)
      else
        __purge_category_tag_tree(child)
      end
    end
  end

  def __delete_pid_from_category_tag_tree(node, pid)
    node['pids'].delete(pid)
    node['children'].each do |child|
      __delete_pid_from_category_tag_tree(child, pid)
    end
  end

  def __recalculate_category_tag_tree_pcount(node)
    pcount = node['pids'].length
    node['children'].each do |child|
      pcount += __recalculate_category_tag_tree_pcount(child)
    end
    node['pcount'] = pcount
    pcount
  end

  def __add_tags_to_category_tag_tree(tag_tree, tags, pid)
    tags.each do |tag|
      tokens = tag.split(",")
      cur = tag_tree
      tokens.each_with_index do |t, i|
        t.strip!
        next if !t || t.length == 0

        # find child node whose name equals to token
        found = false
        cur['children'].each do |child|
          if child['name'] == t
            cur = child
            found = true
            break
          end
        end
        if !found
          new_node = {
            'name' => t,
            'children' => [],
            'pids' => [],
            'pcount' => 0
          }
          cur['children'] << new_node
          cur = new_node
        end

        # if token is last one, add pid
        if i == tokens.length - 1
          cur['pids'] << pid
        end
      end
    end
  end

  UNITS = ["kg", "hundred_g", "item", "animal_item", "bottle", "bulk", "litre", "set", "loc", "vien"]

  def self.get_unit_text(unit)
    I18n.t "admin.#{unit}"
  end

  def unit_as_text
    Product.get_unit_text unit
  end

  def self.is_local_image?(img)
    img && /^\/uploads\/.+$/.match(img)
  end

  def self.is_remote_image?(img)
    img && /^[hH][tT][tT][pP][sS]?:\/\/.+\/.+$/.match(img)
  end

  def has_image?
    images && images.length > 0
  end

  def self.delete_image(img)
    if Product.is_local_image?(img)
      begin
        File.delete("#{Rails.root}/public#{img}")
      rescue
        # ignored
      end
    end
  end

  def in_store?
    quantity > 0
  end

  def in_store_as_text
    in_store? ? I18n.t("client.in_store") : I18n.t("client.not_in_store")
  end

  def category_as_text
    category.name
  end

  def self.general_search(keyword)
    Product.where get_search_criteria(keyword, true)
  end
end

vuhaisan/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  include AdminHelper

  layout "admin"

  before_filter :validate_admin
  before_filter :set_tab_index
  before_filter :load_categories, only: [:index, :new, :edit]
  before_filter :save_image, only: [:create, :update]
  before_filter :prepare_config
  before_filter :make_custom_fields, only: [:create, :update]
  before_filter :make_tags, only: [:create, :update]

  def set_tab_index
    @tab = 0
  end

  def load_categories
    @categories = Category.all.to_a
  end

  def save_image
    params[:product][:images] = []
    params.keys.each do |k|
      if /^_image_\d+$/.match k
        data = params[k]
      end
      if data && data.is_a?(ActionDispatch::Http::UploadedFile)
        filename = SecureRandom.hex
        File.open(Rails.root.join('public', 'uploads', filename), 'wb') do |file|
          file.write(data.read)
        end
        params[:product][:images] << "/uploads/#{filename}"
      elsif data && data.is_a?(String)
        data.strip!
        if Product.is_remote_image?(data) || Product.is_local_image?(data)
          params[:product][:images] << data
        end
      end
    end
  end

  def make_custom_fields
    custom_fields = {}
    params.keys.each do |k|
      if /^_custom_field_name_\d+$/.match(k)
        id = k.scan(/.*(\d+)/).first.first
        name = params[k].to_sym
        options = params["_custom_field_options_#{id}".to_sym].split(",")
        options.each {|o| o.strip! }
        custom_fields[name] = options
      end
    end
    params[:product][:custom_fields] = custom_fields
  end

  def make_tags
    tags = []
    params.keys.each do |k|
      if /^_tag_\d+$/.match(k)
        t = params[k].strip
        tags << t  if t && t.length > 0
      end
    end
    params[:product][:tags] = tags
  end

  def index
    @keyword = params[:keyword]
    if @keyword && @keyword.length > 0
      criteria = Product.general_search @keyword
    else
      criteria = Product.all
    end

    criteria = criteria.order_by([[:updated_at, :desc]])

    @products = criteria.page(params[:page]).per(10)
    @title = I18n.t "admin.product_list"
    render "admin/product/index"
  end

  def new
    @title = I18n.t "admin.create_product"
    @product = Product.new
    render "admin/product/new"
  end

  def create
    Product.create params[:product]
    redirect_to products_path
  end

  def edit
    @product = Product.where(id: params[:id]).first
    if !@product
      redirect_to products_path
    else
      @title = I18n.t "admin.edit_product"
      render "admin/product/edit"
    end
  end

  def update
    @product = Product.where(id: params[:id]).first
    if @product
      if @product.has_image?
        removed = []
        @product.images.each do |i|
          if  Product.is_local_image?(i) && !params[:product][:images].find_index(i)
            Product.delete_image i
          end
        end
      end
      @product.update_attributes params[:product]
    end
    redirect_to products_path
  end

  def destroy
    product = Product.where(id: params[:id]).first
    if product
      product.delete
    end
    redirect_to products_path
  end
end

vuhaisan/app/views/admin/product/_custom_fields.html.erb
<script type="text/javascript">
  function addEmptyCustomField() {
    addCustomField(
      "",
      "",
      "<%= t 'admin.custom_field.name'%>",
      "<%= t 'admin.custom_field.options'%>"
    );
  }
</script>
<div class="form-group">
  <label><%= t "admin.custom_fields" %></label>
  <div id="customFieldInputs">
  </div>
  <div style="clear:both;">
    <button type="button" class="btn btn-default" onclick="addEmptyCustomField();return false;">
      <span class="glyphicon glyphicon-plus"></span>
    </button>
  </div>
</div>

vuhaisan/app/views/admin/product/_images.html.erb
<div class="form-group">
  <label><%= t "admin.image" %></label>
  <div id="imageInputs">
  </div>
  <div style="clear:both;">
    <button type="button" class="btn btn-default" onclick="addImageLink();return false;">
      <span class="glyphicon glyphicon-plus"></span>Link
    </button>
    <button type="button" class="btn btn-default" onclick="addImageUpload();return false;">
      <span class="glyphicon glyphicon-plus"></span>Upload
    </button>
  </div>
</div>

vuhaisan/app/views/admin/product/_tags.html.erb
<div class="form-group">
  <label><%= t "admin.tags" %></label>
  <div id="tagInputs">
  </div>
  <div style="clear:both;">
    <button type="button" class="btn btn-default" onclick="addTag('');return false;">
      <span class="glyphicon glyphicon-plus"></span>
    </button>
  </div>
</div>

vuhaisan/app/views/admin/product/edit.html.erb
<script type="text/javascript" src="/ckeditor/ckeditor.js"></script>

<%= form_for(
      @product,
      html: { :multipart => true },
      role: 'form') do |f| %>

  <%= render partial: 'admin/product/images' %>

  <script type="text/javascript">
    $(function() {
      <% if @product.images && @product.images.length > 0 %>
        <% @product.images.each do |i| %>
          addImageLinkWithData("<%= i %>");
        <% end %>
      <% end %>
    });
  </script>

  <div class="form-group">
    <label><%= t "admin.name" %></label>
    <%= f.text_field :name, required: :required, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label><%= t "admin.unit" %></label>
    <%
      unit_opts = []
      Product::UNITS.each do |u|
        unit_opts << [Product.get_unit_text(u), u]
      end
    %>
    <%= f.select(
          :unit,
          options_for_select(unit_opts, @product.unit),
          {},
          {
            class: 'form-control',
            style: 'width: 200px;'
          }) %>
  </div>
  <div class="form-group">
    <label><%= t "admin.price" %></label>
    <%= f.text_field :price, required: :required, type: :number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label><%= t "admin.quantity" %></label>
    <%= f.text_field :quantity, required: :required, type: :number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label><%= t "admin.category" %></label>
    <%
      cate_opts = []
      @categories.each do |c|
        cate_opts << [c.name, c.id]
      end
    %>
    <%= f.select(
          :category_id,
          options_for_select(cate_opts, @product.category_id),
          {},
          {
            class: 'form-control',
            style: 'width: 200px;'
          }) %>
  </div>
  <div class="form-group">
    <label><%= t "admin.desc" %></label>
    <%= f.text_area :desc, rows: 5, cols: 40, class: "ckeditor form-control" %>
  </div>
  
  <%= render partial: 'admin/product/custom_fields' %>

  <script type="text/javascript">
    $(function() {
      <% @product.custom_fields.each do |name, options| %>
        addCustomField(
          "<%= name %>",
          "<%= options.join(', ') %>",
          "<%= t 'admin.custom_field.name'%>",
          "<%= t 'admin.custom_field.options'%>");
      <% end %>
    });
  </script>

  <%= render partial: 'admin/product/tags' %>

  <script type="text/javascript">
    $(function() {
      <% @product.tags.each do |t| %>
        addTag("<%= t %>");
      <% end %>
    })
  </script>

  <%= f.submit t("admin.edit"), class: 'btn btn-warning' %>
<% end %>

<script type="text/javascript">
  productNewEdit();
</script>

vuhaisan/app/views/admin/product/index.html.erb
<%= form_tag(
      products_path,
      method: 'get',
      role: 'form',
      class: 'form-inline') do %>
  <div class="form-group">
    <%= text_field_tag :keyword, @keyword, class: 'form-control' %>
  </div>
  <%= submit_tag t("admin.search"), class: 'btn btn-primary' %>
  <%= submit_tag(
        t("admin.clear"),
        class: 'btn btn-danger',
        onclick: "location.href='#{products_path}';return false;") %>
<% end %>
<p><%= t "admin.product_search_hint" %></p>

<br/>

<%= button_to t("admin.create"), new_product_path, method: :get, class: 'btn btn-success' %>

<%= paginate @products %>
<br/>
<table class="table table-hover table-bordered table-striped table-condensed">
  <tr>
    <th><%= t "admin.image" %></th>
    <th><%= t "admin.name" %></th>
    <th><%= t "admin.unit" %></th>
    <th><%= t "admin.price" %></th>
    <th><%= t "admin.quantity" %></th>
    <th><%= t "admin.category" %></th>
    <th><%= t "admin.desc" %></th>
    <th></th>
  </tr>
  <% @products.each do |p| %>
    <tr>
      <td>
        <% if p.has_image? %>
          <a href="<%= p.images[0] %>"><img src="<%= p.images[0] %>" height="50" /></a>
        <% end %>
      </td>
      <td><%= p.name %></td>
      <td><%= Product.get_unit_text p.unit %></td>
      <td><%= number_to_currency p.price, unit: "", precision: 0 %></td>
      <td><%= p.quantity %></td>
      <td><%= p.category.name %></td>
      <td>
        <% if p.desc && p.desc.length > 0 %>
          <div class="desc_<%= p.id.to_s %>" style="display:none; width:480px;"><%= p.desc.html_safe %></div>
          <button class="seeMoreButton btn btn-info" data="desc_<%= p.id.to_s %>"><%= t("admin.see_more") %></button>
        <% end %>
      </td>
      <td>
        <%= button_to(
              t("admin.edit"),
              edit_product_path(p.id),
              method: :get,
              class: 'btn btn-warning',
              style: 'float:left; margin-right:10px;') %>
        <%= button_to(
              t("admin.delete"),
              p,
              method: :delete,
              onclick: "return confirm('#{t("admin.confirm_delete")}');",
              class: 'btn btn-danger') %>
      </td>
    </tr>
  <% end %>
</table>
<%= paginate @products %>

<script type="text/javascript">
  productIndex();
</script>

vuhaisan/app/views/admin/product/new.html.erb
<script type="text/javascript" src="/ckeditor/ckeditor.js"></script>

<%= form_for(
      @product,
      html: { :multipart => true },
      role: 'form') do |f| %>

  <%= render partial: 'admin/product/images' %>

  <div class="form-group">
    <label><%= t "admin.name" %></label>
    <%= f.text_field :name, required: :required, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label><%= t "admin.unit" %></label>
    <%
      unit_opts = []
      Product::UNITS.each do |u|
        unit_opts << [Product.get_unit_text(u), u]
      end
    %>
    <%= f.select(
          :unit,
          options_for_select(unit_opts, @product.unit),
          {},
          {
            class: 'form-control',
            style: 'width: 200px;'
          }) %>
  </div>
  <div class="form-group">
    <label><%= t "admin.price" %></label>
    <%= f.text_field :price, required: :required, type: :number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label><%= t "admin.quantity" %></label>
    <%= f.text_field :quantity, required: :required, type: :number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label><%= t "admin.category" %></label>
    <%
      cate_opts = []
      @categories.each do |c|
        cate_opts << [c.name, c.id]
      end
    %>
    <%= f.select(
          :category_id,
          options_for_select(cate_opts, @product.category_id),
          {},
          {
            class: 'form-control',
            style: 'width: 200px;'
          }) %>
  </div>
  <div class="form-group">
    <label><%= t "admin.desc" %></label>
    <%= f.text_area :desc, rows: 5, cols: 40, class: "ckeditor form-control" %>
  </div>

  <%= render partial: 'admin/product/custom_fields' %>

  <%= render partial: 'admin/product/tags' %>
  
  <%= f.submit t("admin.create"), class: 'btn btn-success' %>
<% end %>

<script type="text/javascript">
  productNewEdit();
</script>