vuhaisan/config/routes.rb
Vuhaisan::Application.routes.draw do
  scope "admin" do
    resources :products
    resources :categories
    resources :admin_sessions, only: [:new, :create]
    resources :settei, only: [:edit, :update]
    resources :users, only: [:index]
    resources :orders, only: [:index, :edit, :update]
    resources :kensakus, only: [:index]
    match "logout", to: "admin_sessions#logout", as: :admin_logout
    match "categories_index_update/:id", to: "categories#categories_index_update", as: :admin_categories_index_update
  end

  scope "client" do
    match "home", to: "client#home", as: :client_home
    match "product/:id", to: "client#product_detail", as: :client_product_detail
    match "add_to_cart", to: "client#add_to_cart", as: :client_add_to_cart
    match "add_to_cart_remote", to: "client#add_to_cart_remote", as: :client_add_to_cart_remote, format: :js
    match "remove_from_cart_remote", to: "client#remove_from_cart_remote", as: :client_remove_from_cart_remote_remote, format: :js
    match "cart", to: "client#cart_detail", as: :client_cart_detail
    match "confirm", to: "client#confirm", as: :client_confirm
    match "profile", to: "client#profile", as: :client_profile
    match "update_profile", to: "client#update_profile", as: :client_update_profile
    match "login_remote", to: "client#login_remote", as: :client_login_remote, format: :js
    match "logout", to: "client#logout", as: :client_logout
    match "logout_remote", to: "client#logout_remote", as: :client_logout_remote
    match "update_order_delivery_info", to: "client#update_order_delivery_info", as: :client_update_order_delivery_info
    match "delete_cart", to: "client#delete_cart", as: :client_delete_cart
    match "order/:code", to: "client#order", as: :client_order
    match "info", to: "client#info", as: :client_info
  end
  scope "payment" do
    match "vtc", to: "payment#vtc", as: :payment_vtc
  end

end

vuhaisan/app/models/category.rb
class Category
  include Mongoid::Document

  field :name, type: String
  field :no, type: Integer
  field :hidden, type: Boolean, default: false
  field :tag_tree, type: Hash, default: {
    'name' => "",
    'children' => [],
    'pids' => [],
    'pcount' => 0
  }

  has_many :products, class_name: Product.name, inverse_of: :category

  validates :name, uniqueness: true

  before_create do |document|
  	document.no = Category.count
  end

  before_save do |doc|
    __sort_tag_tree_node(doc.tag_tree)

    if doc.hidden_changed?
      doc.products.each do |p|
        p.hidden = doc.hidden
        p.save
      end
    end
  end

  def __sort_tag_tree_node(node)
    if node['children'].length > 0
      node['children'].sort! { |left, right|
        is_left_leaf = left['children'].length == 0
        is_right_leaf = right['children'].length == 0
        if is_left_leaf == is_right_leaf
          left['name'] <=> right['name']
        else
          if is_left_leaf
            1
          else
            -1
          end
        end
      }
      node['children'].each do |child|
        __sort_tag_tree_node(child)
      end
    end
  end

  def self.get_client_categories_criteria
  	Category.where(hidden: false).order_by([[:no, :asc]])
  end

  def has_tag_tree?
    tag_tree && tag_tree['pcount'] > 0
  end
end

vuhaisan/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  include AdminHelper

  layout "admin"

  before_filter :validate_admin
  before_filter :set_tab_index
  before_filter :prepare_config

  def set_tab_index
    @tab = 1
  end

  def index
    @title = I18n.t "admin.category_list"
    @categories = Category.all.order_by([[:no, :asc]]).to_a
    render "admin/category/index"
  end

  def new
    @title = I18n.t "admin.create_category"
    @category = Category.new
    render "admin/category/new"
  end

  def create
    @category = Category.new params[:category]

    if !@category.save
      @title = I18n.t "admin.create_category"
      @error = I18n.t "admin.err_category_name_exist"
      render "admin/category/new"
    else
      redirect_to categories_path
    end
  end

  def edit
    @title = I18n.t "admin.edit_category"
    @category = Category.where(id: params[:id]).first
    render "admin/category/edit"
  end

  def update
    @category = Category.where(id: params[:id]).first
    if !@category
      redirect_to categories_path
    elsif !@category.update_attributes(params[:category])
      @title = I18n.t "admin.edit_category"
      @error = I18n.t "admin.err_category_name_exist"
      render "admin/category/edit"
    else
      redirect_to categories_path
    end
  end

  def destroy
    # delete category
    cat = Category.where(id: params[:id]).first
    if cat
      cat.delete
      Category.where(no: {"$gt" => cat.no}).to_a.each do |c|
        c.no = c.no - 1
        c.save
      end
    end

    # delete related products
    products = Product.where(category_id: params[:id]).to_a
    products.each do |p|
      p.delete
    end

    redirect_to categories_path
  end

  def categories_index_update
    id = params[:id]
    action = params[:update].to_s
    cat = Category.where(id: id).first
    if cat
      if action == 'up' && cat.no > 0
        other_cat = Category.where(no: cat.no - 1).first
        t = cat.no
        cat.no = other_cat.no
        other_cat.no = t
      elsif action == 'down' && cat.no < Category.count - 1
        other_cat = Category.where(no: cat.no + 1).first
        t = cat.no
        cat.no = other_cat.no
        other_cat.no = t
      elsif action == 'toggle_hidden'
        cat.hidden = !cat.hidden
      end
      cat.save
      other_cat.save if other_cat
    end
    redirect_to categories_path
  end
end

vuhaisan/app/views/admin/category/edit.html.erb
<%= form_for @category, role: 'form' do |f| %>
  <label><%= t "admin.name" %></label>
  <%= f.text_field :name, required: :required, class: 'form-control' %>
  <br/>
  <%= f.submit t("admin.edit"), class: 'btn btn-warning' %>
<% end %>

vuhaisan/app/views/admin/category/index.html.erb
<br/>
<%= button_to t("admin.create"), new_category_path, method: :get, class: 'btn btn-success' %>
<br/>
<table class="table table-hover table-bordered table-striped table-condensed">
  <tr>
    <th>No</th>
    <th><%= t "admin.name" %></th>
    <th><%= t "admin.n_products" %></th>
    <th><%= t "admin.client_page" %></th>
    <th></th>
  </tr>
  <% @categories.each_with_index do |c, index| %>
    <tr>
      <td><%= c.no %></td>
      <td><%= c.name %></td>
      <td><%= link_to c.products.length, products_path(keyword: c.name) %></td>
      <td>
        <%= link_to(
                t("admin.client_page"),
                client_home_path(category_id: c.id, ignore_hidden: true),
                target: "_blank") %>
      </td>
      <td>
        <%= button_to(
              t("admin.edit"),
              edit_category_path(c.id),
              method: :get,
              class: 'btn btn-warning',
              style: 'float:left; margin-right:10px;') %>

        <%= button_to(
              t("admin.delete"),
              c,
              method: :delete,
              onclick: "return confirm('#{t("admin.confirm_delete")}');",
              class: 'btn btn-danger',
              style: 'float:left; margin-right:10px;') %>
        
        <button class="btn btn-default" style='float:left; margin-right:10px;'
                <% if index > 0 %>
                onclick="location.href='<%= admin_categories_index_update_path(id: c.id, update: :up) %>'"
                <% end %>>
          <span class="glyphicon glyphicon-chevron-up"></span>
        </button>

        <button class="btn btn-default" style='float:left; margin-right:10px;'
                <% if index < @categories.length - 1 %>
                onclick="location.href='<%= admin_categories_index_update_path(id: c.id, update: :down) %>'"
                <% end %>>
          <span class="glyphicon glyphicon-chevron-down"></span>
        </button>

        <button class="btn btn-default" style='float:left;'
                onclick="location.href='<%= admin_categories_index_update_path(id: c.id, update: :toggle_hidden) %>'">
          <% if c.hidden %>
            <span class="glyphicon glyphicon-eye-close"></span>
          <% else %>
            <span class="glyphicon glyphicon-eye-open"></span>
          <% end %>
        </button>        
        
      </td>
    </tr>
  <% end %>
</table>

vuhaisan/app/views/admin/category/new.html.erb
<%= form_for @category, role: 'form' do |f| %>
  <label><%= t "admin.name" %></label>
  <%= f.text_field :name, required: :required, class: 'form-control' %>
  <br/>
  <%= f.submit t("admin.create"), class: 'btn btn-primary' %>
<% end %>