vuhaisan/config/routes.rb
Vuhaisan::Application.routes.draw do
  scope "admin" do
    resources :products
    resources :categories
    resources :admin_sessions, only: [:new, :create]
    resources :settei, only: [:edit, :update]
    resources :users, only: [:index]
    resources :orders, only: [:index, :edit, :update]
    resources :kensakus, only: [:index]
    match "logout", to: "admin_sessions#logout", as: :admin_logout
    match "categories_index_update/:id", to: "categories#categories_index_update", as: :admin_categories_index_update
  end

  scope "client" do
    match "home", to: "client#home", as: :client_home
    match "product/:id", to: "client#product_detail", as: :client_product_detail
    match "add_to_cart", to: "client#add_to_cart", as: :client_add_to_cart
    match "add_to_cart_remote", to: "client#add_to_cart_remote", as: :client_add_to_cart_remote, format: :js
    match "remove_from_cart_remote", to: "client#remove_from_cart_remote", as: :client_remove_from_cart_remote_remote, format: :js
    match "cart", to: "client#cart_detail", as: :client_cart_detail
    match "confirm", to: "client#confirm", as: :client_confirm
    match "profile", to: "client#profile", as: :client_profile
    match "update_profile", to: "client#update_profile", as: :client_update_profile
    match "login_remote", to: "client#login_remote", as: :client_login_remote, format: :js
    match "logout", to: "client#logout", as: :client_logout
    match "logout_remote", to: "client#logout_remote", as: :client_logout_remote
    match "update_order_delivery_info", to: "client#update_order_delivery_info", as: :client_update_order_delivery_info
    match "delete_cart", to: "client#delete_cart", as: :client_delete_cart
    match "order/:code", to: "client#order", as: :client_order
    match "info", to: "client#info", as: :client_info
  end
  scope "payment" do
    match "vtc", to: "payment#vtc", as: :payment_vtc
  end

end

vuhaisan/app/controllers/client_controller.rb
class ClientController < ApplicationController

  include PaymentHelper
  include ClientHelper

  before_filter :prepare, only: [
    :home,
    :product_detail,
    :cart_detail,
    :profile,
    :add_to_cart,
    :add_to_cart_remote,
    :remove_from_cart_remote,
    :confirm,
    :order,
    :info
  ]
  before_filter :prepare_selected_categories, only: [:home]
  before_filter :prepare_profile, only: [
    :profile,
    :update_profile,
    :cart_detail,
    :confirm,
    :order
  ]
  before_filter :prepare_product_custom_fields, only: [:add_to_cart, :add_to_cart_remote]

  layout "client"

  def prepare
    prepare_categories
    prepare_cart
  end

  def prepare_product_custom_fields
    @custom_field_values = []
    params.keys.each do |k|
      if /^_custom_field_value_\d+$/.match(k)
        @custom_field_values << params[k]
      end
    end
  end

  def home
    @keyword = params[:keyword]
    @keyword.strip! if @keyword
    if @keyword && @keyword.length > 0
      criteria = Product.general_search @keyword
      @category_id = nil
    else
      criteria = Product.where(category_id: @category_id)
    end

    if request.method == "POST" && @keyword && @keyword.length > 0
      __log_search(@keyword, criteria.length)
      redirect_to client_home_path(keyword: @keyword)
      return
    end

    if @category_id
      @category = Category.where(id: @category_id).first

      tag_tree_path = params[:tag_tree_path]
      tag_tree_path.strip! if tag_tree_path
      if  tag_tree_path &&
          tag_tree_path.length > 0 &&
          @category &&
          @category.has_tag_tree?
        splitted = tag_tree_path.split(',')
        @tag_tree_path = []
        splitted.each do |t|
          next if !t || t.length == 0
          @tag_tree_path << t
        end
        current_node = @category.tag_tree
        @tag_tree_path.each do |t|
          next_child = nil
          current_node['children'].each do |child|
            if child['name'] == t
              next_child = child
              break
            end
          end
          if next_child
            current_node = next_child
          else
            break
          end
        end
        if current_node
          criteria = criteria.where(id: { '$in' => current_node['pids'] })
        end
      end
    end

    # do not show hidden product (product whose category is hidden)
    if !params[:ignore_hidden]
      criteria = criteria.where(hidden: false)
    end

    # sort by updated_at
    criteria = criteria.order_by([[:updated_at, :desc]])

    @products = criteria.page(params[:page]).per(10)

    @title = I18n.t("client.home")
    render "client/home"
  end

  def __log_search(keyword, n_results)
    if keyword && keyword.length > 0
      kensaku = Kensaku.where(keyword: keyword).first
      if kensaku
        kensaku.n_searches = kensaku.n_searches + 1
        kensaku.last_n_results = n_results
        kensaku.save
      else
        Kensaku.create(
          keyword: keyword,
          n_searches: 1,
          last_n_results: n_results)
      end
    end
  end

  def product_detail
    id = params[:id]
    @product = Product.where(id: id).first
    @title = @product.name
    if !@product
      redirect_to client_home_path
    else
      render "client/product_detail"
    end 
  end

  def add_to_cart
    common_add_to_cart
    redirect_to client_home_path(category_id: @category_id)
  end

  def add_to_cart_remote
    common_add_to_cart
    @product_id = params[:product_id]
    render "client/remote/add_to_cart_remote", layout: nil
  end

  def common_add_to_cart
    product = Product.where(id: params[:product_id]).first
    quantity = params[:quantity].to_i

    # check if product is already added
    existing_item = nil
    @cart.items.each do |i|
      if  i.product_id == product.id &&
          i.unit == product.unit &&
          i.price == product.price &&
          i.custom_field_values == @custom_field_values
        existing_item = i
        break
      end
    end

    # if item exists -> accumulate
    # else -> create new item
    if existing_item
      existing_item.quantity += quantity
    else
      item = OrderItem.new(
        unit: product.unit,
        quantity: quantity,
        price: product.price,
        custom_field_values: @custom_field_values)
      if @custom_field_values.length > 0
        item.name = "#{product.name} - #{item.custom_field_values_as_text}"
      else
        item.name = product.name
      end
      item.product = product
      @cart.items << item
    end

    # save cart to db
    @cart.save
  end

  def remove_from_cart_remote
    item_id = params[:item_id]

    @item = nil
    @cart.items.each do |i|
      if i.id.to_s == item_id
        @item = i
        break
      end
    end

    if @item
      @cart.items.delete @item
    end

    @cart.save

    render "client/remote/remove_from_cart_remote"
  end

  def cart_detail
    @title = I18n.t("client.cart_detail")
    render "client/cart"
  end

  def confirm
    if @cart && @cart.sum_quantity > 0
      payment = params[:payment].to_i
      
      @cart.name = params[:name]
      @cart.email = params[:email]
      @cart.phone = params[:phone]
      @cart.payment = payment
      @cart.step = Order::STEP_SENT
      if @user
        @cart.user = @user
      end

      # generate address
      arr = [params[:address][:detail]]
      arr << params[:address][:district] if params[:address][:district]
      arr << params[:address][:province]
      @cart.address = arr.join(", ")

      # generate ship cost
      location_data_lv1 = LOCATION_DATA[params[:address][:province]]
      if location_data_lv1.is_a?(Integer)
        @cart.ship_cost = location_data_lv1
      elsif location_data_lv1.is_a?(Hash)
        @cart.ship_cost = location_data_lv1[params[:address][:district]]
      end

      # notify user by email
      if @cart.should_mail?
        UserMailer.order_changed_email(@cart).deliver
      end

      @cart.save

      if payment == Order::PAYMENT_VTC_PAY
        redirect_to get_vtc_pay_url(@cart)
      else
        prepare_cart
        @title = I18n.t("client.message")
        if payment == Order::PAYMENT_AT_DELIVERIED
          @message = I18n.t("client.confirm_success_at_delivery")
        elsif payment == Order::PAYMENT_BANK_TRANSFER
          @message = I18n.t("client.confirm_success_bank_transfer")
        end
        render "client/message"
      end
    else
      redirect_to client_cart_detail_path
    end
  end

  def profile
    if @user
      @order_keyword = params[:order_keyword]
      @order_keyword.strip! if @order_keyword
      if @order_keyword && @order_keyword.length > 0
        criteria = Order.general_search @order_keyword
      else
        criteria = Order.all
      end

      @orders = criteria.where(step: {'$gt' => Order::STEP_CARTING})
                  .where(user_id: @user.id)
                  .order_by([[:updated_at, :desc]])
                  .page(params[:page]).per(10)
      @title = I18n.t("client.profile")
      render "client/profile"
    else
      @title = I18n.t("client.message")
      @error = I18n.t 'client.err_user_not_logged_in'
      render "client/message"
    end
  end

  def update_profile
    if @user
      @user.update_attributes(
        name: params[:name],
        email: params[:email],
        address: params[:address],
        phone: params[:phone]
      )
    end
    redirect_to client_home_path
  end

  def login_remote
    session[:fb_id] = params[:fb_id]
    render "client/remote/login_remote"
  end

  def logout
    session[:fb_id] = nil
    redirect_to client_home_path
  end

  def logout_remote
    session[:fb_id] = nil
    render 'client/remote/logout_remote'
  end

  def delete_cart
    session[:cart_order_id] = nil
    if @cart
      @cart.delete
    end
    redirect_to client_home_path
  end

  def order
    @order = Order.where(code: params[:code]).first

    if @order
      if @order.user
        if !@user
          __order_not_logged_in
          return
        end
        if @user.id != @order.user_id
          __order_not_found
          return
        end
      end
    else
      __order_not_found
      return
    end

    @title = I18n.t "client.order_detail"
    render "client/order_detail"
  end

  def __order_not_found
    @title = I18n.t("client.message")
    @error = I18n.t 'client.err_order_not_found'
    render "client/message"
  end

  def __order_not_logged_in
    @title = I18n.t("client.message")
    @error = I18n.t 'client.err_user_not_logged_in'
    render "client/message"
  end

  def info
    @title = I18n.t('client.info')
    @settei = Settei.first
    if !@settei
      redirect_to client_home_path
    else
      render 'client/info'
    end
  end
end

vuhaisan/app/helpers/client_helper.rb
module ClientHelper
  def prepare_categories
    @categories = Category.get_client_categories_criteria.to_a
  end

  def prepare_selected_categories
    @category_id =
      params[:category_id] ||
      Category.get_client_categories_criteria.only(:id).first.id.to_s
  end

  def prepare_cart
    if session[:cart_order_id]
      @cart = Order.where(id: session[:cart_order_id], step: Order::STEP_CARTING).first
    end
    if !@cart
      @cart = Order.create
      session[:cart_order_id] = @cart.id.to_s
    end
  end

  def prepare_profile
    fb_id = session[:fb_id]
    if fb_id
      @user = User.where(fb_id: fb_id).first
      if !@user
        @user = User.create(fb_id: fb_id)
      end
    end
  end
end

vuhaisan/app/views/client/_currency.html.erb
<%
  id = SecureRandom.uuid
  cssClass = '' if !cssClass
%>
<span id='<%= id %>' class='<%= cssClass %>'>
</span>
<script type="text/javascript">
  (function() {
    if (!window.changeCurrencyVal) {
      window.changeCurrencyVal = function($elem, val) {
        if (!(typeof val === 'number')) {
          val = parseInt(val);
        }
        $elem.attr('data', val);
        $elem.html(val.format(0, 3));
      }
    }
    if (!window.getCurrencyVal) {
      window.getCurrencyVal = function($elem) {
        var val = $elem.attr('data');
        if (typeof val === 'number') {
          return val;
        } else {
          return parseInt(val);
        }
      }
    }
    changeCurrencyVal($('#<%= id %>'), <%= val %>)
  }).call();
</script>

vuhaisan/app/views/client/_product_info.html.erb
<p class="name"><%= product.name %></p>
<p class="price">
  <%= number_to_currency product.price, unit: "", precision: 0 %>
  /
  <%= Product.get_unit_text product.unit %>
</p>
<p class="in_store <%= !product.in_store? ? "not_in_store" : "" %>">
  <%= product.in_store_as_text %>
</p>

vuhaisan/app/views/client/cart.html.erb
<div id="cartDetail" align="center">
  <%= form_tag client_confirm_path, method: "post" do %>
  <table>

    <tr><td id="deliveryInfo">
      <div>
        <span class="groupTitle">1. <%= t("client.delivery_info") %></span>
        <hr/>
      </div>
      <% if @user %>
        <div>
          <input id="useProfileCheck" type='checkbox'/>
          <span class="use_profile"><%= t("client.use_profile") %></span>
        </div>
      <% end %>
      <table>
        <tr>
          <td class="label" align="right"><%= t("client.name") %>(*)</td>
          <td>
            <%= text_field_tag(
                  :name,
                  nil,
                  type: :text,
                  required: :required,
                  class: :text) %></td>
        </tr>
        <tr>
          <td class="label" align="right"><%= t("client.email") %></td>
          <td>
            <%= text_field_tag(
                  :email,
                  nil,
                  type: :email,
                  class: :text) %></td>
        </tr>
        <tr>
          <td class="label" align="right"><%= t("client.address") %>(*)</td>
          <td>
            <%= render(
                  partial: 'address',
                  locals: {
                    address: nil,
                    shipCostCallback: 'shipCostCallback' }) %>
          </td>
        </tr>
        <tr>
          <td class="label" align="right"><%= t("client.phone") %>(*)</td>
          <td>
            <%= text_field_tag(
                  :phone,
                  nil,
                  type: :tel,
                  required: :required,
                  class: :text) %></td>
        </tr>
      </table>
      <div>
        <span class="read_email_for_delivery_info">
          <%= t("client.read_email_for_delivery_info") %>
        </span>
      </div>
    </td></tr>
      
    <tr><td>
      <div id="deliveryMethod">
        <div>
          <span class="groupTitle">2. <%= t("client.delivery_method") %></span>
          <hr/>
        </div>
        <div class="content">
          <%= Settei.first.delivery_method.html_safe %>
        </div>
      </div>
    </td></tr>

    <tr><td>
      <div id="orderItems">
        <div>
          <span class="groupTitle">3. <%= t("client.order_items") %></span>
          <hr/>
        </div>
        <%= render partial: "order_item_list", locals: {order: @cart} %>
        <br/>
        <%= radio_button_tag(
              :payment,
              Order::PAYMENT_AT_DELIVERIED,
              Order::PAYMENT_AT_DELIVERIED == @cart.payment,
              onclick: "updateSubmitButton('#{t 'client.confirm'}');") %>
        <%= Order.get_payment_as_text Order::PAYMENT_AT_DELIVERIED %>
        <%= link_to '[?]', "#{client_info_path}#pay_at_delivery", target: '_blank' %>
        <br/>
        <%= radio_button_tag(
              :payment,
              Order::PAYMENT_BANK_TRANSFER,
              Order::PAYMENT_BANK_TRANSFER == @cart.payment,
              onclick: "updateSubmitButton('#{t 'client.confirm'}');") %>
        <%= Order.get_payment_as_text Order::PAYMENT_BANK_TRANSFER %>
        <%= link_to '[?]', "#{client_info_path}#pay_bank_transfer", target: '_blank' %>

        <script type="text/javascript">
          function updateSubmitButton(val) {
            $("form input[type=submit]").val(val);
          }
        </script>
      </div>
    </td></tr>

    <tr><td>
      <% if @cart.sum_quantity > 0 %>
        <div style="margin-top:30px;" align="left">
          <%= submit_tag t("client.confirm"), class: "blueButton"  %>
          <button id="deleteOrderButton" class="redButton"
            style="margin-left:20px;"><%= t("client.delete_cart") %>
          </button>
        </div>
      <% end %>
    </td></tr>

  </table>
  <% end %>
</div>

<script type="text/javascript">
  <% if @user %>
    cart(
      "<%= client_delete_cart_path %>",
      "<%= client_remove_from_cart_remote_remote_path %>",
      "<%= @user.name %>",
      "<%= @user.email %>",
      <%= @user.address.to_json.html_safe %>,
      "<%= @user.phone %>"
    );
  <% else %>
    cart(
      "<%= client_delete_cart_path %>",
      "<%= client_remove_from_cart_remote_remote_path %>",
      null,
      null,
      null,
      null);
  <% end %>

  function shipCostCallback(shipCost) {
    changeOrderShipCost(shipCost);
    updateOrderSum();
  }
</script>

vuhaisan/app/views/client/home.html.erb
<div id="productList" align="center">
  <table>
    <tr>
      <td colspan="2">
        <div id="facepile" class="fbsp" style="margin-bottom:10px;">
          <fb:facepile
            href="<%= get_fanpage %>"
            max_rows="1"
            colorscheme="light"
            size="medium"
            show_count="true">
          </fb:facepile>
          <br/>
          <div class="fb-like" data-href="<%= get_fanpage %>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"
            style="margin-top:10px;"></div>
        </div>
      </td>
    <tr>
      <% if @category && @category.has_tag_tree? %>
        <td style="vertical-align:top;">
          <%= render partial: 'tag_tree', locals: {
                  category: @category,
                  selected_path: @tag_tree_path } %>
        </td>
      <% else %>
        <td style="width:0px;"></td>
      <% end %>
      <% if @products && @products.length > 0 %>
        <td style="width:600px;vertical-align:top;  ">
          <% @products.each_with_index do |p, i| %>
            <% product_detail_link = client_product_detail_path(p.id) %>
            <a href="<%= product_detail_link %>">
              <div class="product">
                <table style="width:100%;" cellpadding="0" cellspacing="0">
                  <tr>
                    <td class="col1">
                      <%= render partial: "product_info", locals: {product: p} %>
                    </td>
                    <td align="right" class="col2">
                      <% if p.has_image? %>
                        <img src="<%= p.images[0] %>" id="<%= p.id.to_s %>_img"/>
                      <% end %>
                    </td>
                  <tr>
                </table>
              </div>
            </a>
            <div class="footer">
                <% product_detail_full_link = "#{request.protocol}#{request.host_with_port}#{product_detail_link}" %>
                <table style="float:left;">
                  <tr>
                    <td>
                      <div  class="fb-like fbsp" 
                            data-href="<%= product_detail_full_link %>" 
                            data-layout="button_count" 
                            data-action="like" 
                            data-show-faces="false" 
                            data-share="true"></div>
                    </td>
                    <td>
                      <%= image_tag "comment.png", class: 'commentCountImg fbsp' %>
                    </td>
                    <td>
                      <fb:comments-count 
                          class="count" 
                          href="<%= product_detail_full_link %>" 
                          style="float:left;"></fb:comments-count>
                    </td>
                  </tr>
                </table>
                <% if p.in_store? && p.custom_fields.empty? %>
                <div class="addToCartButton" data-product-id="<%= p.id.to_s %>">
                  <%= image_tag "cart12.png", title: t("client.add_to_cart") %>
                </div>
                <% end %>
            </div>
          <% end %>
        </td>
      <% else %>
        <td>
          <div align="center">
            <h2><%= t 'client.no_product' %></h2>
          </div>
        </td>
      <% end %>
    </tr>
    <tr>
      <td colspan="2">
        <div style='float:right'>
          <%= paginate @products %>
        </div>
      </td>
    </tr>
  </table>
</div>

<script type="text/javascript">
  home("<%= client_add_to_cart_remote_path %>");
</script>

vuhaisan/app/views/client/info.html.erb
<div id="info" align="center">
  <div style="width: 60%;" align="left">
    <div class="well">
      <h3 id="delivery_method"><%= t("client.delivery_method") %></h3>
      <hr/>
      <p><%= @settei.delivery_method.html_safe %></p>
    </div>

    <div class="well">
      <h3 id="pay_at_delivery"><%= t("client.pay_at_delivery") %></h3>
      <hr/>
      <p><%= @settei.payment_at_delivery.html_safe %></p>
    </div>

    <div class="well">
      <h3 id="pay_bank_transfer"><%= t("client.pay_bank_transfer") %></h3>
      <hr/>
      <p><%= @settei.payment_bank_transfer.html_safe %></p>
    </div>
    
    <div class="well">
      <h3 id="steps_desc"><%= t("client.steps_desc") %></h3>
      <hr/>
      <p><%= @settei.steps_desc.html_safe %></p>
    </div>

    <div class="well">
      <h3 id="search_hint"><%= t("client.search_hint") %></h3>
      <hr/>
      <p><%= @settei.search_hint.html_safe %></p>
    </div>

    <div class="well">
      <h3 id="policy"><%= t("client.policy") %></h3>
      <hr/>
      <p><%= @settei.policy.html_safe %></p>
    </div>
  </div>
</div>

vuhaisan/app/views/client/order_detail.html.erb
<div id="orderDetail" align="center">
  <div style="width:60%" align="left">
    
    <table>
      <tr>
        <td class="label" align="right"><%= t "client.code" %></td>
        <td><%= @order.code %></td>
      </tr>
      <tr>
        <td class="label" align="right"><%= t "client.payment_method" %></td>
        <td><%= @order.payment_as_text %></td>
      </tr>
      <tr>
        <td class="label" align="right"><%= t "client.status" %></td>
        <td>
          <%= @order.step_as_text %>
          <%= link_to '[?]', "#{client_info_path}#steps_desc", target: '_blank' %>
        </td>
      </tr>

      <tr>
        <td class="label" align="right"><%= t "client.history" %></td>
        <td>
          <%= render partial: 'common/order_history', locals: { order: @order } %>
        </td>
      </tr>
    </table>

    <hr/>

    <table>
      <tr>
        <td class="label" align="right"><%= t("client.name") %></td>
        <td><%= @order.name %></td>
      </tr>
      <tr>
        <td class="label" align="right"><%= t("client.email") %></td>
        <td><%= @order.email %></td>
      </tr>
      <tr>
        <td class="label" align="right"><%= t("client.address") %></td>
        <td><%= @order.address %></td>
      </tr>
      <tr>
        <td class="label" align="right"><%= t("client.phone") %></td>
        <td><%= @order.phone %></td>
      </tr>
    </table>

    <hr/>

    <%= render partial: "order_item_list", locals: {order: @order} %>

    <br/>
    
    <% if @order.payment == Order::PAYMENT_VTC_PAY && @order.step < Order::STEP_PAID %>
      <%= button_to  t("client.pay"), get_vtc_pay_url(@order), class: "blueButton" %>
    <% end %>

  </div>
</div>

vuhaisan/app/views/client/product_detail.html.erb
<div id="product_detail">
  <div class="col1">
    <% if @product.has_image? %>
      <img  src="<%= @product.images[0] %>"
            data-glisse-big="<%= @product.images[0] %>"
            class="productImage"
            rel="group1" />
      <% if @product.images.length > 1 %>
        <% @product.images.each_with_index do |img, index| %>
          <% next if index == 0 %>
          <% if index % 2 == 1 %>
            <img  src="<%= img %>"
                  data-glisse-big="<%= img %>"
                  class="productImage"
                  style="clear:both;float:left;width:50%"
                  rel="group1" />
          <% else %>
            <img  src="<%= img %>"
                  data-glisse-big="<%= img %>"
                  class="productImage"
                  style="float:left;width:50%"
                  rel="group1" />
          <% end %>
        <% end %>
      <% end %>
      <script type="text/javascript">
        $(function() {
          $(".productImage").glisse({
            changeSpeed: 550, 
            speed: 500,
            effect:'rotate',
            fullscreen: false
          });
        });
      </script>
    <% end %>
  </div>
  <div class="col2">
    <div class="info">
      <%= render partial: "product_info", locals: {product: @product} %>
    </div>
    <% if @product.in_store? %>
      <%= form_tag client_add_to_cart_path(product_id: @product.id.to_s, category_id: @category_id), method: "post", class: "add_to_cart_form" do %>
        <span class="label"><%= t("client.select_quantity") %></span>
        <%
          quantity_opts = []
          (1..@product.quantity).each do |q|
            quantity_opts << [q, q]
          end
        %>
        <%= select_tag :quantity, options_for_select(quantity_opts, 1), id: "quantity_select" %>
        <span class="label" style="margin-left:20px;"><%= t("client.total") %>:</span>
        <span id="total"><%= @product.price %></span>
        <br/>
        <% custom_field_id = 0 %>
        <% @product.custom_fields.each do |name, options| %>
          <span class="label"><%= name %></span>
          <%= hidden_field_tag "_custom_field_name_#{custom_field_id}", name %>
          <%
            options_opts = []
            options.each do |o|
              options_opts << [o, o]
            end
          %>
          <%= select_tag(
                "_custom_field_value_#{custom_field_id}",
                options_for_select(options_opts, 1),
                id: "quantity_select") %>
          <br/>
          <% custom_field_id = custom_field_id + 1 %>
        <% end %>
        <%= submit_tag t("client.add_to_cart"), class: "blueButton", style: "margin-top:10px;" %>
      <% end %>
    <% end %>
    <div class="desc"><%= @product.desc.html_safe %></div>
    <br/>
    <!--
    <div class="fb-like fbsp" data-href="<%= get_request_url %>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
    <div class="fbComments fbsp">
      <fb:comments href="<%= get_request_url %>" numposts="5" colorscheme="light"></fb:comments>
    </div>
    -->
  </div>
</div>

<script type="text/javascript">
  var price = <%= @product.price %>;
  var total = price;
  var $totalText = $("#total");
  $totalText.html(total.format(0, 3));
  $("#quantity_select").change(function() {
    total = parseInt($(this).val()) * price;
    $totalText.html(total.format(0, 3));
  });
</script>

vuhaisan/app/views/client/profile.html.erb
<div id="profileDetail" align="center">
  <div class="well" style="width:55%;">
    <%= form_tag client_update_profile_path, method: "post" do %>
      <table cellpadding="10" style="margin-bottom: 10px;">
        <tr>
          <td align="right"><b><%= t("client.name") %>(*)</b></td>
          <td>
            <%= text_field_tag(
                  :name,
                  @user.name,
                  type: :text,
                  required: :required,
                  class: :text) %></td>
        </tr>
        <tr>
          <td align="right"><b><%= t("client.email") %></b></td>
          <td>
            <%= text_field_tag(
                  :email,
                  @user.email,
                  type: :email,
                  class: :text) %></td>
        </tr>
        <tr>
          <td align="right"><b><%= t("client.address") %>(*)</b></td>
          <td>
            <%= render(
                  partial: 'client/address',
                  locals: {
                    address: @user.address,
                    shipCostCallback: nil }) %>
          </td>
        </tr>
        <tr>
          <td align="right"><b><%= t("client.phone") %>(*)</b></td>
          <td>
            <%= text_field_tag(
                  :phone,
                  @user.phone,
                  type: :tel,
                  required: :required,
                  class: :text) %></td>
        </tr>
      </table>
      <%= submit_tag t("client.update"), class: "blueButton" %>
      <button id="logoutButton" class="redButton" style="margin-left:20px;"><%= t("client.logout") %></button>
    <% end %>
  </div>

  <br/>
  <br/>

  <div style="width:60%;" align="left">
    <h3><%= t 'client.order.list' %></h3>
    <hr/>
    <div style="float:left;margin-top:20px;margin-bottom:20px;">
      <%= form_tag client_profile_path, method: :get do %>
        <%= text_field_tag(
              :order_keyword,
              @order_keyword,
              style: 'width:350px;height:30px;padding:2px;',
              placeholder: t('client.order.search_hint')) %>
        <%= link_to '[?]', "#{client_info_path}#search_hint", target: '_blank' %>
      <% end %>
    </div>
    <% if @orders && @orders.length > 0 %>
      <div style="clear:both;">
        <table class="client_data_table clickable_table" style="width:100%">
          <tr>
            <th><%= t "client.code" %></th>
            <th><%= t "client.desc" %></th>
            <th><%= t "client.total" %></th>
            <th><%= t "client.status" %></th>
            <th><%= t "client.update" %></th>
          </tr>
          <% @orders.each do |o| %>
            <tr onclick="location.href='<%= client_order_path(o.code) %>'">
              <td><%= o.code %></td>
              <td><%= o.desc %></td>
              <td><%= number_to_currency o.sum, unit: "", precision: 0 %></td>
              <td>
                <%= o.step_as_text %>
                <%= link_to '[?]', "#{client_info_path}#steps_desc", target: '_blank' %>
              </td>
              <td>
                <%= render partial: "common/datetime", locals: { val: o.updated_at } %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div style='float:right'>
        <%= paginate @orders %>
      </div>
    <% else %>
      <div style="clear:both;">
        <h2><%= t 'client.no_order' %></h2>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  profile("<%= client_logout_path %>");
</script>